server:
  port: ${SERVICE_PORT:7081}

spring:
# h2
  datasource:
    driverClassName: ${DB_DRIVER:org.h2.Driver}
    url: ${DB_URL:jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1}
    username: ${DB_LOGIN:sa}
    password: ${DB_PASSWORD:}
  jpa:
    database-platform: ${JPA_DIALECT:org.hibernate.dialect.H2Dialect}
    generate-ddl: ${GENERATE_DDL:true}
    hibernate:
      naming: 
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
