server:
  port: ${SERVICE_PORT}
  servlet:
    context-path: /${SERVICE_NAME:demo} 

spring:
  profiles:
    include: shared

eureka:
  client:
    enabled: true
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true